### ISSUE TITLE
how to save the image as picture file and upload it into PHP server?

### ISSUE THREAD

**Issue by ghost** [bcabanes/ng-camera#14]
I was wondering if it is possible to save the captured image into a file (.jpg, .png, etc) and upload it later into php server.. How can I do this? When i have my research angularjs is lack of support about ng-camera specially for those beginners. Please update.

**Comment by alexcoroza** [comment]
This plugin passes base64 image to "snapshot" value, so just try to research how to upload it in php.

**Comment by ghost** [comment]
i get it... finally..
